# Site settings
title:          Gerald
description:    "Minimal Jekyll theme for storytellers"
url:            "https://gerald8.github.io/"

# Author
author:
  name:         Gerald
  url:          https://gerald8.github.io/
  email:        melowwx@gmail.com

# Build settings
markdown:       kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

excerpt_separator: <!--more-->

encoding: UTF-8
